##  loading the data set


In [1]:
from google.colab import files
uploaded=files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads.csv


In [2]:
import numpy as np
import pandas as pd
import io

In [3]:
df=pd.read_csv('Social_Network_Ads.csv')

In [4]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
df.shape

(400, 5)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


## Checking the Categorical columns and performing the Encoding method

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le=LabelEncoder()

In [10]:
df.Gender=le.fit_transform(df.Gender)

In [11]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

In [12]:
df.Gender.value_counts()

0    204
1    196
Name: Gender, dtype: int64

##Spliting of X and y

In [24]:
X=df.drop(columns=['Purchased'],axis=1)

In [25]:
X.head()

User ID  Gender  Age  EstimatedSalary
0  15624510       1   19            19000
1  15810944       1   35            20000
2  15668575       0   26            43000
3  15603246       0   27            57000
4  15804002       1   19            76000

In [26]:
y=df.Purchased

In [27]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

## 9. Scaling the Independent Variables

In [28]:
from sklearn.preprocessing import MinMaxScaler

In [29]:
scale=MinMaxScaler()

In [30]:
X_scaled=pd.DataFrame(scale.fit_transform(X),columns=X.columns)

In [31]:
X_scaled.head()

User ID  Gender       Age  EstimatedSalary
0  0.232636     1.0  0.023810         0.029630
1  0.982732     1.0  0.404762         0.037037
2  0.409926     0.0  0.190476         0.207407
3  0.147083     0.0  0.214286         0.311111
4  0.954801     1.0  0.023810         0.451852

## Train Test Split

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.25,random_state=0)

In [33]:
X_train

User ID  Gender       Age  EstimatedSalary
250  0.979235     0.0  0.619048         0.177778
63   0.068365     1.0  0.333333         0.777778
312  0.673012     0.0  0.476190         0.259259
159  0.129356     0.0  0.333333         0.888889
283  0.388498     0.0  0.809524         0.044444
..        ...     ...       ...              ...
323  0.212338     0.0  0.714286         0.111111
192  0.856546     1.0  0.261905         0.207407
117  0.099555     1.0  0.428571         0.274074
47   0.843539     0.0  0.214286         0.288889
172  0.917219     0.0  0.190476         0.762963

[300 rows x 4 columns]

In [34]:
X_train.shape

(300, 4)

In [35]:
y_train

250    0
63     1
312    0
159    1
283    1
      ..
323    1
192    0
117    0
47     0
172    0
Name: Purchased, Length: 300, dtype: int64

In [36]:
y_train.shape

(300,)

In [37]:
X_test

User ID  Gender       Age  EstimatedSalary
132  0.639601     1.0  0.285714         0.533333
309  0.344848     0.0  0.476190         0.259259
341  0.845534     1.0  0.404762         0.444444
196  0.691052     0.0  0.285714         0.474074
246  0.286924     0.0  0.404762         0.259259
..        ...     ...       ...              ...
146  0.740906     0.0  0.214286         0.600000
135  0.045533     1.0  0.119048         0.355556
390  0.970231     1.0  0.714286         0.133333
264  0.135548     1.0  0.714286         0.555556
364  0.353120     1.0  0.571429         0.659259

[100 rows x 4 columns]

In [38]:
X_test.shape

(100, 4)

##Building the Model

In [39]:
from sklearn.linear_model import LinearRegression

In [40]:
MLR=LinearRegression()

In [41]:
MLR.fit(X_train,y_train)

LinearRegression()

In [42]:
y_pred=MLR.predict(X_test)

In [43]:
y_pred

array([ 0.21161882,  0.30203095,  0.28350177,  0.1798365 ,  0.22624388,
       -0.15473973, -0.00966961,  0.60671907, -0.1624405 ,  0.51874746,
        0.07247899,  0.01588336,  0.25914512,  0.45126907, -0.06351712,
        0.36819006,  0.3488927 , -0.11077594,  1.06678687,  0.0943471 ,
        0.22218047,  0.88417606,  0.37865087,  0.73264719, -0.172389  ,
        0.92346606,  0.17739841,  0.16520584,  0.32830337,  0.30220132,
        0.01409798,  0.39012653,  0.79889506,  0.29238119, -0.05940775,
       -0.25010741, -0.01333314,  0.18753578,  0.0476514 ,  0.55521069,
        0.12481064,  0.38055916,  0.15786752,  0.05861488,  0.66356546,
        0.04049574,  0.35466067,  0.80425017, -0.12814345,  0.74271118,
        1.05560004,  0.10578515,  0.27305179,  0.46966907,  1.02048771,
        0.38998097,  0.16719592,  0.12302624,  0.46681724, -0.21355669,
        0.0302908 ,  0.81431669, -0.14499954,  0.42512869, -0.29942978,
        0.97957257,  0.05748348,  0.01738265,  0.35312835,  0.46

In [44]:
y_test

132    0
309    0
341    0
196    0
246    0
      ..
146    1
135    0
390    1
264    1
364    1
Name: Purchased, Length: 100, dtype: int64

In [45]:
pd.DataFrame({'Actual_y':y_test,'predicted_y':y_pred})

Actual_y  predicted_y
132         0     0.211619
309         0     0.302031
341         0     0.283502
196         0     0.179836
246         0     0.226244
..        ...          ...
146         1     0.163424
135         0    -0.028338
390         1     0.455776
264         1     0.735577
364         1     0.616387

[100 rows x 2 columns]

In [46]:
train_pred=MLR.predict(X_train)

In [47]:
train_pred

array([ 3.75483595e-01,  4.32678817e-01,  2.79883286e-01,  4.90424172e-01,
        5.57307032e-01,  9.29685142e-01,  2.89837798e-01,  3.23248161e-01,
        2.57945745e-01,  2.79937314e-01,  1.08611742e-01,  2.11170192e-01,
        4.89670169e-01,  5.14292732e-01,  7.35452959e-01,  6.54451403e-01,
        7.61333614e-01,  2.30573298e-01,  6.49384918e-01,  5.51193919e-01,
       -1.99772391e-01,  1.10321817e+00,  5.54060752e-01,  5.31936690e-01,
        3.79917021e-01,  2.64140995e-01,  5.12441619e-01,  8.58205411e-01,
        5.08803683e-01,  4.06783358e-01, -1.61371749e-01,  8.56535302e-01,
       -2.01904368e-01,  7.80025637e-01,  6.91021437e-01,  8.47322351e-02,
        5.13981180e-01,  1.76079523e-01,  4.48343354e-01,  4.00324641e-01,
        2.31426705e-01, -7.02426166e-02,  2.26444601e-01,  4.99295121e-01,
        2.77282467e-01,  5.50938663e-01,  4.55746885e-01,  1.00483437e+00,
        6.26871243e-01,  3.09989418e-01,  2.91801256e-01,  3.03680254e-01,
        3.68536676e-01,  

In [48]:
test_pred=MLR.predict(X_test)

In [49]:
test_pred

array([ 0.21161882,  0.30203095,  0.28350177,  0.1798365 ,  0.22624388,
       -0.15473973, -0.00966961,  0.60671907, -0.1624405 ,  0.51874746,
        0.07247899,  0.01588336,  0.25914512,  0.45126907, -0.06351712,
        0.36819006,  0.3488927 , -0.11077594,  1.06678687,  0.0943471 ,
        0.22218047,  0.88417606,  0.37865087,  0.73264719, -0.172389  ,
        0.92346606,  0.17739841,  0.16520584,  0.32830337,  0.30220132,
        0.01409798,  0.39012653,  0.79889506,  0.29238119, -0.05940775,
       -0.25010741, -0.01333314,  0.18753578,  0.0476514 ,  0.55521069,
        0.12481064,  0.38055916,  0.15786752,  0.05861488,  0.66356546,
        0.04049574,  0.35466067,  0.80425017, -0.12814345,  0.74271118,
        1.05560004,  0.10578515,  0.27305179,  0.46966907,  1.02048771,
        0.38998097,  0.16719592,  0.12302624,  0.46681724, -0.21355669,
        0.0302908 ,  0.81431669, -0.14499954,  0.42512869, -0.29942978,
        0.97957257,  0.05748348,  0.01738265,  0.35312835,  0.46

## Measuring the Performance using Metrics

In [50]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()

In [51]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [52]:
test_pred=model.predict(X_test)

In [53]:
train_pred=model.predict(X_train)

In [54]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [55]:
print('Testing accuracy:',accuracy_score(y_test,test_pred))

Testing accuracy: 0.93


In [56]:
print('Training accuracy:',accuracy_score(y_train,train_pred))

Training accuracy: 1.0


In [57]:
pd.crosstab(y_test,test_pred)

col_0       0   1
Purchased        
0          64   4
1           3  29

In [58]:
print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.96      0.94      0.95        68
           1       0.88      0.91      0.89        32

    accuracy                           0.93       100
   macro avg       0.92      0.92      0.92       100
weighted avg       0.93      0.93      0.93       100

